In [58]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

#import os
#for dirname, _, filenames in os.walk('/kaggle/input'):
#    for filename in filenames:
#        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [59]:
data = "test_input.csv"
test_input = pd.read_csv(data)


data = "train.csv"
train_input = pd.read_csv(data)
df =train_input.copy()
df1=test_input.copy()

In [60]:
del df['LASTAUTOPAYTIME']
del df['TIMEDEPAVG12']
del df['BLNAMNT03']

del df1['LASTAUTOPAYTIME']
del df1['TIMEDEPAVG12']
del df1['BLNAMNT03']

In [61]:

dolar =   {"2018-03-31" : 3.9560,"2018-04-30" : 4.0472, "2018-05-31" : 4.4889 ,
           "2018-06-30" : 4.5690,"2018-07-31" : 4.9087, "2018-08-31" : 6.5616 ,
           "2018-09-30" : 6.0010,"2018-10-31" : 5.5080, "2018-11-30" : 5.1663 ,
           "31.12.2018" : 5.2905
         }
tufe_yıl= {"2018-03-31" : 10.23,"2018-04-30" : 10.85, "2018-05-31" : 12.15,
           "2018-06-30" : 15.39,"2018-07-31" : 15.85, "2018-08-31" : 17.90,
           "2018-09-30" : 24.52,"2018-10-31" : 25.24, "2018-11-30" : 21.62,
           "31.12.2018" : 20.30
          }
tufe_ay=  {"2018-03-31" : 0.99, "2018-04-30" : 1.87, "2018-05-31" : 1.62 ,
           "2018-06-30" : 2.61, "2018-07-31" : 0.55, "2018-08-31" : 2.30 ,
           "2018-09-30" : 6.30, "2018-10-31" : 2.67, "2018-11-30" :-1.44 ,
           "31.12.2018" : -0.40 
         }
bist30 =  {"2018-03-31" : 1401,"2018-04-30" : 1269, "2018-05-31" : 1279,
           "2018-06-30" : 1181,"2018-07-31" : 1194, "2018-08-31" : 1144,
           "2018-09-30" : 1239,"2018-10-31" : 1121, "2018-11-30" : 1193,
           "31.12.2018" : 1143
         }
tatil =   {"2018-03-31" : 3, "2018-04-30" : 4 , "2018-05-31" : 4,
           "2018-06-30" : 0, "2018-07-31" : 10, "2018-08-31" : 0,
           "2018-09-30" : 1, "2018-10-31" : 0 , "2018-11-30" : 7,
           "31.12.2018" : 1
        }


df['Dolar']     = df["TRAN_DATE"].map(dolar)    
df['Tufe_Ay']   = df["TRAN_DATE"].map(tufe_ay )    
df['Tufe_Yıl']  = df["TRAN_DATE"].map(tufe_yıl)    
df['Tatil']     = df["TRAN_DATE"].map(tatil)
df['Bist30']    = df["TRAN_DATE"].map(bist30)


del df["TRAN_DATE"]

In [4]:
# knn imputation strategy and prediction for the hose colic dataset
import numpy as np

from sklearn.impute import KNNImputer
#del df["CUSTNBR"]

In [9]:
imputer   = KNNImputer(n_neighbors=5)
df_filled = imputer.fit_transform(df)

In [12]:
df_deneme = pd.DataFrame(df_filled)
liste= []

liste.append(df.columns)

df_deneme.columns = liste
df_deneme

,CUSTNBR,ADDCONTAMNT,ACCMVMTAVG,ACCAMNTAVG03,ACCACVNUM12,ACCAMNTAVG12,CARDDINSUM12,DISTNUM12,INTPHNNUM03,INTLOGNUM12,...,CONTDEBTNUM,CONTMONTHAMNT,RTRNDESVAMNT,MAXTIMECONTR,CONTCOLLAMNT,Dolar,Tufe_Ay,Tufe_Yıl,Tatil,Bist30
0,22776.0,0.0,641.0,155.8,100.0,396.0,204.0,100.0,100.0,100.0,...,104.0,340.0,272.0,104.0,2926.0,3.9560,0.99,10.23,3.0,1401.0
1,22234.0,0.0,50477.0,122.0,100.0,570.4,100.0,107.0,258.0,126.0,...,100.0,328.0,467.0,102.0,2704.0,5.5080,2.67,25.24,0.0,1121.0
2,19974.0,0.0,1461.0,1593.0,108.0,2268.0,203.0,117.0,779.0,328.0,...,101.0,268.0,256.0,104.0,2620.0,5.1663,-1.44,21.62,7.0,1193.0
3,148625.0,0.0,9723.0,111.0,100.0,7173.0,100.0,123.0,316.0,164.0,...,100.0,328.0,297.0,102.0,2884.0,3.9560,0.99,10.23,3.0,1401.0
4,46344.0,0.0,2124.0,125.4,100.0,2498.0,413.2,100.0,129.0,356.0,...,104.0,268.0,785.0,106.0,2104.0,5.1663,-1.44,21.62,7.0,1193.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173584,63639.0,0.0,836.0,820.0,101.0,1299.0,100.0,101.0,165.0,140.0,...,101.0,3068.0,6305.0,106.0,23741.0,3.9560,0.99,10.23,3.0,1401.0
173585,82692.0,0.0,612.0,447.0,100.0,2003.0,212.8,100.0,100.0,101.0,...,100.0,340.0,2402.0,107.0,12244.0,5.1663,-1.44,21.62,7.0,1193.0
173586,164868.0,2500.0,3592.0,33700.0,100.0,6732.0,6742.0,116.0,566.0,263.0,...,100.0,220.0,18154.0,106.0,66220.0,5.1663,-1.44,21.62,7.0,1193.0
173587,156758.0,1300.0,1529.0,18222.0,100.0,7569.0,189.0,117.0,405.0,185.0,...,100.0,340.0,759.0,104.0,5554.0,4.0472,1.87,10.85,4.0,1269.0
173588,167849.0,0.0,1329.0,6218.0,100.0,801.0,1158.0,100.0,100.0,100.0,...,100.0,398.0,1875.0,107.0,12690.0,6.0010,6.30,24.52,1.0,1239.0

In [13]:
df_deneme.to_csv("islenmis.csv")

In [5]:
data_frame = pd.read_csv("islenmis.csv")

In [6]:
df = data_frame.copy()
import seaborn as sn
import matplotlib.pyplot as plt
corrMatrix = df.corr(method = "spearman" )
fig, ax = plt.subplots(figsize=(50,50))         # Sample figsize in inches
sn.heatmap(corrMatrix, annot=True, linewidths=.5, ax=ax)
plt.show()

'\nimport seaborn as sn\nimport matplotlib.pyplot as plt\ncorrMatrix = df.corr(method = "spearman" )\nfig, ax = plt.subplots(figsize=(50,50))         # Sample figsize in inches\nsn.heatmap(corrMatrix, annot=True, linewidths=.5, ax=ax)\nplt.show()\n'

In [7]:

for i in range(corrMatrix.shape[0]):
    for j in range(i+1, corrMatrix.shape[0]):
        if corrMatrix.iloc[i,j] >= 0.80:
            print(corrMatrix.iloc[i,j])

"""
Dolar -> Tufe_Yıl 0.87
Contcollamnt -> Rtrndesvamnt 0.82
Contcollamnt -> Crrastal     0.80
Contcollamnt -> Desaccuamnt  0.98
Intlognum12  -> Intphnum03   0.95


"""

'\nDolar -> Tufe_Yıl 0.87\nContcollamnt -> Rtrndesvamnt 0.82\nContcollamnt -> Crrastal     0.80\nContcollamnt -> Desaccuamnt  0.98\nIntlognum12  -> Intphnum03   0.95\n\n\n'

In [8]:
del df["CONTCOLLAMNT"]
del df["INTPHNNUM03"]
"""
corrMatrix = df.corr(method = "spearman" )
for i in range(corrMatrix.shape[0]):
    for j in range(i+1, corrMatrix.shape[0]):
        if corrMatrix.iloc[i,j] >= 0.80:
            print(corrMatrix.iloc[i,j])
"""

'\ncorrMatrix = df.corr(method = "spearman" )\nfor i in range(corrMatrix.shape[0]):\n    for j in range(i+1, corrMatrix.shape[0]):\n        if corrMatrix.iloc[i,j] >= 0.80:\n            print(corrMatrix.iloc[i,j])\n'

In [9]:
"""
AYLIK ORTALAMA KATKI MıKTARI         CONTMONTHAMNT
SON 12 AYDA INTERNETE GIRIS SAYISI   INTLOGNUM12
SON 12 AYDA TELEFONA ISLEM SAYISI    DISTNUM12


TELEFONDAN ISLEM SAYISI
----------------------- *AYLIK ORTLAMA KATKI MİKTARI
INTERNETE GIRIS SAYSISI 
"""
df[['CONTMONTHAMNT', 'INTLOGNUM12', 'DISTNUM12']].describe()

       CONTMONTHAMNT    INTLOGNUM12      DISTNUM12
count  173589.000000  173589.000000  173589.000000
mean      524.064031     259.088773     124.800022
std       736.219693     269.563549      47.677580
min       101.000000     100.000000     100.000000
25%       328.000000     100.000000     100.000000
50%       340.000000     154.000000     108.000000
75%       460.000000     317.000000     131.000000
max     51100.000000    7828.000000    3333.000000

In [10]:
 min(df["RTRNDESVAMNT"])

-467736.0

In [12]:
#gapminder['continent']df
df["Aktiflik"] = np.dot(df['DISTNUM12'], df['CONTMONTHAMNT'])/df['INTLOGNUM12']

In [13]:
df2 = df["RTRNDESVAMNT"].copy()
df2.sort_values(inplace = True)

In [14]:
len(df2)

173589

In [15]:
df2= pd.DataFrame(df2, columns =["RTRNDESVAMNT"])
df2.reset_index(inplace = True)
del df2["index"]
len(df2)

173589

In [16]:
liste =df2["RTRNDESVAMNT"].unique()
print(liste[2147 *0])
print(liste[2147 *1])
print(liste[2147 *2])
print(liste[2147 *3])
print(liste[2147 *4])
print(liste[2147 *5])
print(liste[2147 *6])
print(liste[2147 *7])
print(liste[2147 *8])
print(liste[2147 *9])

-467736.0
1642.0
4220.0
6863.0
9814.0
13433.0
18380.0
26132.0
39090.0
70245.0

In [17]:
#davranış ekle

def davranis_ekle(df):
    df.loc[(df['RTRNDESVAMNT'] >=- 467736.0) & (df['RTRNDESVAMNT'] < 1642.0),  'DAVRANIS'] = 'CAT_1'
    df.loc[(df['RTRNDESVAMNT'] >= 1642.0)    & (df['RTRNDESVAMNT'] < 4220.0),  'DAVRANIS'] = 'CAT_2'
    df.loc[(df['RTRNDESVAMNT'] >= 4220.0)    & (df['RTRNDESVAMNT'] < 6863.0),  'DAVRANIS'] = 'CAT_3'
    df.loc[(df['RTRNDESVAMNT'] >= 6863.0)    & (df['RTRNDESVAMNT'] < 9814.0),  'DAVRANIS'] = 'CAT_4'
    df.loc[(df['RTRNDESVAMNT'] >= 9814.0)    & (df['RTRNDESVAMNT'] < 13433.0), 'DAVRANIS'] = 'CAT_5'
    df.loc[(df['RTRNDESVAMNT'] >= 13433.0)   & (df['RTRNDESVAMNT'] < 18380.0), 'DAVRANIS'] = 'CAT_6'
    df.loc[(df['RTRNDESVAMNT'] >= 18380.0)   & (df['RTRNDESVAMNT'] < 26132.0), 'DAVRANIS'] = 'CAT_7'
    df.loc[(df['RTRNDESVAMNT'] >= 26132.0)   & (df['RTRNDESVAMNT'] < 39090.0), 'DAVRANIS'] = 'CAT_8'
    df.loc[(df['RTRNDESVAMNT'] >= 39090.0)   & (df['RTRNDESVAMNT'] < 70245.0), 'DAVRANIS'] = 'CAT_9'
    df.loc[(df['RTRNDESVAMNT'] >= 70245.0), 'DAVRANIS'] = 'CAT_10'
davranis_ekle(df)

davranis ={"CAT_1"  : 20, "CAT_2"  : 3,  "CAT_3"  : 6,  "CAT_4"  : 18, "CAT_5" : 14, 
           "CAT_6"  : 15, "CAT_7"  : 4,  "CAT_8"  : 12, "CAT_9"  : 16, "CAT_10" : 10, 
           
        }


df['davranıs_cod']  = df["DAVRANIS"].map(davranis)

In [18]:
del df["DAVRANIS"]
del df["CONTPAIDAMNT07"]
del df["DEBTAVG00"]
del df["CONTPAIDAMNT02"]
del df["Tatil"]
del df["davranıs_cod"]
del df["CONTDEBTNUM"]
del df["DISTNUM12"] 
del df["Tufe_Ay"]

In [19]:
from sklearn.model_selection import train_test_split, GridSearchCV
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from catboost import CatBoostRegressor

In [20]:
from sklearn.preprocessing import StandardScaler

X = df.drop('ADDCONTAMNT', axis=1)
y = df["ADDCONTAMNT"]
del df["Unnamed: 0"]

scaled_cols=StandardScaler().fit_transform(X)
scaled_cols=pd.DataFrame(scaled_cols, columns=X.columns)



X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                                    test_size=0.20, 
                                                    random_state=46)

In [21]:
del X_train["Unnamed: 0"]

In [22]:
from xgboost import XGBRegressor

In [23]:
xgb  = XGBRegressor().fit(X_train, y_train)
catb = CatBoostRegressor(verbose = False).fit(X_train,y_train)

In [24]:
models      = []
sonuc_ilkel = []
sonuc       = []

In [25]:
models.append(("XGBoost", xgb))
models.append(("CatBoost", catb))

In [26]:
del X_test["Unnamed: 0"]

In [27]:
from sklearn.metrics import mean_squared_error

In [28]:
for name, modelobj in models:
        y_pred = modelobj.predict(X_test)
        rmse   = np.sqrt(mean_squared_error(y_test, y_pred))
        sonuc_ilkel.append((name,rmse))

In [29]:
sonuc_ilkel_df = pd.DataFrame(sonuc_ilkel,columns = ["Model İsmi","İlkel Test Hatası"])
sonuc_ilkel_df = sonuc_ilkel_df.set_index("Model İsmi")
print(sonuc_ilkel_df)

            İlkel Test Hatası
Model İsmi
XGBoost           6632.134957
CatBoost          6276.939372

In [33]:
dolar =   {"2018-03-31" : 3.9560,"2018-04-30" : 4.0472, "2018-05-31" : 4.4889 ,
           "2018-06-30" : 4.5690,"2018-07-31" : 4.9087, "2018-08-31" : 6.5616 ,
           "2018-09-30" : 6.0010,"2018-10-31" : 5.5080, "2018-11-30" : 5.1663 ,
           "31.12.2018" : 5.2905
         }
tufe_yıl= {"2018-03-31" : 10.23,"2018-04-30" : 10.85, "2018-05-31" : 12.15,
           "2018-06-30" : 15.39,"2018-07-31" : 15.85, "2018-08-31" : 17.90,
           "2018-09-30" : 24.52,"2018-10-31" : 25.24, "2018-11-30" : 21.62,
           "31.12.2018" : 20.30
          }
tufe_ay=  {"2018-03-31" : 0.99, "2018-04-30" : 1.87, "2018-05-31" : 1.62 ,
           "2018-06-30" : 2.61, "2018-07-31" : 0.55, "2018-08-31" : 2.30 ,
           "2018-09-30" : 6.30, "2018-10-31" : 2.67, "2018-11-30" :-1.44 ,
           "31.12.2018" : -0.40 
         }
bist30 =  {"2018-03-31" : 1401,"2018-04-30" : 1269, "2018-05-31" : 1279,
           "2018-06-30" : 1181,"2018-07-31" : 1194, "2018-08-31" : 1144,
           "2018-09-30" : 1239,"2018-10-31" : 1121, "2018-11-30" : 1193,
           "31.12.2018" : 1143
         }
df1['Dolar']     = df1["TRAN_DATE"].map(dolar)    
df1['Tufe_Ay']   = df1["TRAN_DATE"].map(tufe_ay )    
df1['Tufe_Yıl']  = df1["TRAN_DATE"].map(tufe_yıl)    
df1['Tatil']     = df1["TRAN_DATE"].map(tatil)
df1['Bist30']    = df1["TRAN_DATE"].map(bist30)


del df1["TRAN_DATE"]

df1_X = df1.copy()
df1_y = df1_X["CUSTNBR"].copy()

del df1_X["CUSTNBR"]

In [34]:
imputer     = KNNImputer(n_neighbors=5)
df_filled_X = imputer.fit_transform(df1_X)

In [35]:
df_deneme_X = pd.DataFrame(df_filled_X)
liste_X= []

liste_X.append(df1_X.columns)

df_deneme_X.columns = liste_X
df_deneme_X

,ACCMVMTAVG,ACCAMNTAVG03,ACCACVNUM12,ACCAMNTAVG12,CARDDINSUM12,DISTNUM12,INTPHNNUM03,INTLOGNUM12,DEMINFO1,DEMINFO2,...,CONTDEBTNUM,CONTMONTHAMNT,RTRNDESVAMNT,MAXTIMECONTR,CONTCOLLAMNT,Dolar,Tufe_Ay,Tufe_Yıl,Tatil,Bist30
0,579.0,159.4,102.0,418.0,524.0,104.0,556.0,227.0,58.0,2.0,...,100.0,328.0,124.0,102.0,1438.0,5.2905,-0.4,20.3,1.0,1143.0
1,518.0,980.0,100.0,1239.0,254.4,100.0,443.0,284.0,34.0,2.0,...,104.0,340.0,143.0,106.0,256.0,5.2905,-0.4,20.3,1.0,1143.0
2,2441.0,4631.0,100.0,1832.0,493.0,101.0,930.0,309.0,34.0,2.0,...,100.0,328.0,47.0,101.0,1012.0,5.2905,-0.4,20.3,1.0,1143.0
3,848.0,504.0,100.0,693.0,249.0,100.0,101.0,100.0,43.0,2.0,...,104.0,340.0,237.0,106.0,1042.0,5.2905,-0.4,20.3,1.0,1143.0
4,1709.0,154.0,100.0,760.0,100.0,101.0,222.0,125.0,32.0,2.0,...,104.0,268.0,338.0,105.0,1012.0,5.2905,-0.4,20.3,1.0,1143.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16973,2716.2,242.8,80.8,3158.6,2294.0,112.0,1204.0,398.0,35.0,2.0,...,100.0,268.0,1491.0,105.0,8008.0,5.2905,-0.4,20.3,1.0,1143.0
16974,2470.0,2736.0,100.0,5102.0,297.0,132.0,100.0,101.0,68.0,1.0,...,100.0,460.0,327.0,102.0,5302.0,5.2905,-0.4,20.3,1.0,1143.0
16975,1184.6,235.0,0.0,517.8,119.0,114.0,609.0,215.0,54.0,2.0,...,100.0,376.0,1209.0,105.0,8542.0,5.2905,-0.4,20.3,1.0,1143.0
16976,1296.8,319.4,0.0,1086.2,100.0,100.0,100.0,100.0,84.0,2.0,...,104.0,340.0,1683.0,107.0,7942.0,5.2905,-0.4,20.3,1.0,1143.0
16977,2564.0,3311.0,106.0,3107.0,2206.0,248.0,1545.0,518.0,36.0,3.0,...,101.0,400.0,875.0,104.0,7366.0,5.2905,-0.4,20.3,1.0,1143.0

In [36]:
df_deneme_X.to_csv("islenmis_test.csv")

In [37]:
df_test = pd.read_csv("islenmis_test.csv")
df_test

,Unnamed: 0,ACCMVMTAVG,ACCAMNTAVG03,ACCACVNUM12,ACCAMNTAVG12,CARDDINSUM12,DISTNUM12,INTPHNNUM03,INTLOGNUM12,DEMINFO1,...,CONTDEBTNUM,CONTMONTHAMNT,RTRNDESVAMNT,MAXTIMECONTR,CONTCOLLAMNT,Dolar,Tufe_Ay,Tufe_Yıl,Tatil,Bist30
0,0,579.0,159.4,102.0,418.0,524.0,104.0,556.0,227.0,58.0,...,100.0,328.0,124.0,102.0,1438.0,5.2905,-0.4,20.3,1.0,1143.0
1,1,518.0,980.0,100.0,1239.0,254.4,100.0,443.0,284.0,34.0,...,104.0,340.0,143.0,106.0,256.0,5.2905,-0.4,20.3,1.0,1143.0
2,2,2441.0,4631.0,100.0,1832.0,493.0,101.0,930.0,309.0,34.0,...,100.0,328.0,47.0,101.0,1012.0,5.2905,-0.4,20.3,1.0,1143.0
3,3,848.0,504.0,100.0,693.0,249.0,100.0,101.0,100.0,43.0,...,104.0,340.0,237.0,106.0,1042.0,5.2905,-0.4,20.3,1.0,1143.0
4,4,1709.0,154.0,100.0,760.0,100.0,101.0,222.0,125.0,32.0,...,104.0,268.0,338.0,105.0,1012.0,5.2905,-0.4,20.3,1.0,1143.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16973,16973,2716.2,242.8,80.8,3158.6,2294.0,112.0,1204.0,398.0,35.0,...,100.0,268.0,1491.0,105.0,8008.0,5.2905,-0.4,20.3,1.0,1143.0
16974,16974,2470.0,2736.0,100.0,5102.0,297.0,132.0,100.0,101.0,68.0,...,100.0,460.0,327.0,102.0,5302.0,5.2905,-0.4,20.3,1.0,1143.0
16975,16975,1184.6,235.0,0.0,517.8,119.0,114.0,609.0,215.0,54.0,...,100.0,376.0,1209.0,105.0,8542.0,5.2905,-0.4,20.3,1.0,1143.0
16976,16976,1296.8,319.4,0.0,1086.2,100.0,100.0,100.0,100.0,84.0,...,104.0,340.0,1683.0,107.0,7942.0,5.2905,-0.4,20.3,1.0,1143.0
16977,16977,2564.0,3311.0,106.0,3107.0,2206.0,248.0,1545.0,518.0,36.0,...,101.0,400.0,875.0,104.0,7366.0,5.2905,-0.4,20.3,1.0,1143.0

In [38]:
def davranis_ekle_x(df):
    df.loc[(df['RTRNDESVAMNT'] >=- 467736.0) & (df['RTRNDESVAMNT'] < 1642.0),  'DAVRANIS'] = 'CAT_1'
    df.loc[(df['RTRNDESVAMNT'] >= 1642.0)    & (df['RTRNDESVAMNT'] < 4220.0),  'DAVRANIS'] = 'CAT_2'
    df.loc[(df['RTRNDESVAMNT'] >= 4220.0)    & (df['RTRNDESVAMNT'] < 6863.0),  'DAVRANIS'] = 'CAT_3'
    df.loc[(df['RTRNDESVAMNT'] >= 6863.0)    & (df['RTRNDESVAMNT'] < 9814.0),  'DAVRANIS'] = 'CAT_4'
    df.loc[(df['RTRNDESVAMNT'] >= 9814.0)    & (df['RTRNDESVAMNT'] < 13433.0), 'DAVRANIS'] = 'CAT_5'
    df.loc[(df['RTRNDESVAMNT'] >= 13433.0)   & (df['RTRNDESVAMNT'] < 18380.0), 'DAVRANIS'] = 'CAT_6'
    df.loc[(df['RTRNDESVAMNT'] >= 18380.0)   & (df['RTRNDESVAMNT'] < 26132.0), 'DAVRANIS'] = 'CAT_7'
    df.loc[(df['RTRNDESVAMNT'] >= 26132.0)   & (df['RTRNDESVAMNT'] < 39090.0), 'DAVRANIS'] = 'CAT_8'
    df.loc[(df['RTRNDESVAMNT'] >= 39090.0)   & (df['RTRNDESVAMNT'] < 70245.0), 'DAVRANIS'] = 'CAT_9'
    df.loc[(df['RTRNDESVAMNT'] >= 70245.0), 'DAVRANIS'] = 'CAT_10'
davranis_ekle_x(df_test)

davranis ={"CAT_1"  : 20, "CAT_2"  : 3,  "CAT_3"  : 6,  "CAT_4"  : 18, "CAT_5" : 14, 
           "CAT_6"  : 15, "CAT_7"  : 4,  "CAT_8"  : 12, "CAT_9"  : 16, "CAT_10" : 10, 
           
        }

# df1_y  etiklerleri barındırıyor 
df_test['davranıs_cod']  = df_test["DAVRANIS"].map(davranis)
del df_test["DAVRANIS"]

In [39]:
df_test["Aktiflik"] = np.dot(df_test['DISTNUM12'], df_test['CONTMONTHAMNT'])/df_test['INTLOGNUM12']
#liste_CONTPAIDAMNT= ['CONTPAIDAMNT00', 'CONTPAIDAMNT01', 'CONTPAIDAMNT03','CONTPAIDAMNT04', 'CONTPAIDAMNT05', 'CONTPAIDAMNT06', 'CONTPAIDAMNT08','CONTPAIDAMNT09', 'CONTPAIDAMNT10', 'CONTPAIDAMNT11']
df_test["CONTPAIDAMNT_MEAN"]= (df_test["CONTPAIDAMNT00"]+df_test["CONTPAIDAMNT01"]+df_test["CONTPAIDAMNT03"]+df_test["CONTPAIDAMNT04"]+df_test["CONTPAIDAMNT05"]+df_test["CONTPAIDAMNT06"]+df_test["CONTPAIDAMNT08"]+df_test["CONTPAIDAMNT09"]+df_test["CONTPAIDAMNT10"]+df_test["CONTPAIDAMNT11"])/10

In [40]:
scaled_cols=StandardScaler().fit_transform(df_test)
scaled_cols=pd.DataFrame(scaled_cols, columns=df_test.columns)

In [41]:
del df_test["CONTCOLLAMNT"]
del df_test["INTPHNNUM03"]
del df_test["Unnamed: 0"]
del df_test["DEBTAVG00"]
del df_test["CONTPAIDAMNT02"]
del df_test["Tatil"]
del df_test["davranıs_cod"]
del df_test["CONTDEBTNUM"]
del df_test["DISTNUM12"] 
del df_test["Tufe_Ay"]

In [42]:
y_pred_xgb = xgb.predict(df_test)
y_pred = catb.predict(df_test)

In [43]:
from lightgbm import LGBMRegressor
modelobj = LGBMRegressor().fit(X_train,y_train)
y_pred_lgb = modelobj.predict(df_test)

In [44]:
y_pred

array([-117.55424344,  100.25514585,  118.26857005, ...,  186.99208666,
        105.39086139,  104.17194583])

In [45]:
samplesub = pd.read_csv('sample_submission.csv')
samplesub["Predicted"] = pd.Series(y_pred)
samplesub.to_csv('sample_submission.csv',index=False)

In [55]:
from sklearn.ensemble import ExtraTreesClassifier
from sklearn import preprocessing
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report


#feature_importance_normalized = np.std([tree. for tree in catb], axis = 0)
#accuracy_score(y_train, catb.predict(X_train))
catb.get_feature_importance(prettified=True)

           Feature Id  Importances
0         DESACCUAMNT    11.769936
1            DEMINFO2    10.719885
2      CONTPAIDAMNT05     8.989109
3       ASTAVGDIF0312     4.694357
4      CONTPAIDAMNT04     4.291161
5          ACCMVMTAVG     4.279246
6      CONTPAIDAMNT06     4.248796
7            DEMINFO1     4.056446
8           CRRASTALL     3.795043
9        EFTAMNTSUM12     3.792097
10          MAXMATEVR     3.249361
11       RTRNDESVAMNT     2.942434
12             Bist30     2.932755
13       MAXTIMECONTR     2.738529
14              Dolar     2.643030
15      CONTMONTHAMNT     2.596831
16       ACCAMNTAVG12     2.255535
17       ACCAMNTAVG03     1.797616
18        ACCACVNUM12     1.791693
19           Aktiflik     1.776665
20         LSTPRDCNUM     1.647064
21       CARDDINSUM12     1.617762
22     CONTPAIDAMNT10     1.599938
23  CONTPAIDAMNT_MEAN     1.438336
24        INTLOGNUM12     1.321502
25     CONTPAIDAMNT11     1.309491
26           Tufe_Yıl     1.252412
27     CONTPAIDAMNT09     1.120132
28     CONTPAIDAMNT00     1.034227
29     CONTPAIDAMNT08     0.816588
30     CONTPAIDAMNT01     0.799713
31     CONTPAIDAMNT03     0.682308